config/routes.rb
NerdpursuitFrontend::Application.routes.draw do

  get "sessions/new"
  get "sessions/create"
  get "sessions/failure"
  get '/logout', :to => 'sessions#destroy'
  
  get   '/login', :to => 'sessions#new', :as => :login
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

  resources :questions do
    member do
      put :accept
      put :reject
    end
  end
  
  root :to => "sessions#new"

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  attr_accessible :provider, :uid, :user_id, :token

  belongs_to :user
  validates_presence_of :provider, :uid
end

app/models/question.rb
class Question < ActiveRecord::Base
  include HTTParty  

  attr_accessible :a1, :a2, :a3, :a4, :category, :creator, :creator_github, :creator_twitter, :nerd_level, :right_answer, :sub_category, :text, :user_id, :accepted_at, :rejected_at
  belongs_to :user
  validates_presence_of :a1, :a2, :a3, :a4, :category, :creator, :creator_github, :nerd_level, :right_answer, :sub_category, :text, :user_id

  def update_file_and_commit(file, content, message)
    github = ::Hackn::Github.new(self.user.authorizations.find_by_provider('github').token, self.user)
    tree_sha = github.create_tree("questions/#{self.sub_category}/#{file}", content)
    commit_sha = github.create_commit(tree_sha, message)
    github.point_master_to_commit(commit_sha)
  end

  def formatted_created_at
    self.created_at.strftime("%Y-%m-%d")
  end

  def to_json
    hashie = { "question" => self.attributes.keep_if{ |attribute| %w(sub_category category nerd_level text a1 a2 a3 a4 right_answer creator creator_github creator_twitter).include? attribute}}
    hashie["question"].merge!({"created_at" => self.formatted_created_at})
    hashie.to_json
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :login, :email

  has_many :authorizations
  validates_presence_of :name
  has_many :questions
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user  
    
  private  
  
    def current_user  
      @current_user ||= User.find(session[:user_id]) if session[:user_id]  
    end 
    
    def user_required
      redirect_to login_url unless current_user
    end  

    def admin_required
      user_required
      redirect_to root_url unless current_user.admin?
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_filter :user_required
  before_filter :admin_required, :only => [:index, :show, :accept, :reject]

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def accept
    @question = Question.find(params[:id])
    if @question && @question.update_attribute(:accepted_at, Time.now)
      @question.update_attribute(:rejected_at, nil)
      # send message to user
      @question.update_file_and_commit("#{@question.text.truncate(40).parameterize}.json", @question.to_json, "Added a #{@question.category.upcase} question about #{@question.sub_category.upcase}. NERD LEVEL #{@question.nerd_level}")
      redirect_to questions_url, notice: 'Question was successfully accepted.' 
    else
      redirect_to questions_url, notice: 'Question was NOT successfully accepted.' 
    end
  end

  def reject
    @question = Question.find(params[:id])
    if @question && @question.update_attribute(:rejected_at, Time.now)
      @question.update_attribute(:accepted_at, nil)
      # send message to user      
      redirect_to questions_url, notice: 'Question was successfully rejected.' 
    else
      redirect_to questions_url, notice: 'Question was NOT successfully rejected.' 
    end
  end

  def new
    @question = current_user.questions.build
  end

  def create
    @question = current_user.questions.build(params[:question])
    respond_to do |format|
      if @question.save
        format.html { redirect_to root_url, notice: 'Question was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    auth_hash = request.env['omniauth.auth']
    @authorization = Authorization.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"].to_s)
    if @authorization
      user = @authorization.user
      session[:user_id] = user.id
      redirect_to root_url
    else
      user = User.new :name => auth_hash['extra']['raw_info']['name'], :email => auth_hash['extra']['raw_info']['email'], :login => auth_hash['extra']['raw_info']['login']
      user.authorizations.build :provider => auth_hash["provider"], :uid => auth_hash["uid"].to_s, :token => auth_hash['credentials']['token']
      user.save
      session[:user_id] = user.id
      redirect_to root_url
    end
  end

  def failure
    render :text => "Sorry, but you didn't allow access to our app!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url 
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Questionizer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="header">
    <%= link_to(image_tag("logo.png"), root_url) %>
  </div>
  <p id="notice"><%= notice %></p>
  <%= yield %>
  <br/>
  <div id="footer" class="clearfix">
    <img id="madeby" src="/assets/madeby.png">
  </div>
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-31335165-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Question</legend>

    <div class="control-group">
      <%= f.label :category, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :category, ["programming", "culture", "backend", "frontend", "design", "startup & founding", "social" ] %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :sub_category, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :sub_category, ["algorithms", "api", "bash", "C", "couchdb","css", "culture", "data", "encoding", "flash", "graphics", "haskell", "html","http","javascript", "php", "python","rails","ruby","regex" ] %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :nerd_level, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :nerd_level, ['1','2','3','4', '5'] %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :text, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :text, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :a1, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :a1, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :a2, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :a2, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :a3, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :a3, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :a4, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :a4, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :right_answer, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :right_answer, ['a1','a2','a3','a4'] %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :creator, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :creator, :class => 'text_field', :value => current_user.name %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :creator_twitter, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :creator_twitter, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :creator_github, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :creator_github, :class => 'text_field', :value => current_user.login %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', root_url, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/questions/index.html.erb
<div class="clearfix" id="container">
  <div id="wrapper">
    <div class="view-container">
      <div class="display">
        <div id="view-login" style="display: block;">
          <h2>Questionizer</h2>
          <table>
            <th>Category</th>
            <th>Sub Category</th>
            <th>User</th>
            <th>Status</th>
            <th>Actions</th>                                                
            <% @questions.each do |question| %>
              <tr>
                <td><%= question.category %>,</td>
                <td><%= question.sub_category %> by</td>
                <td><strong><%= question.user.name || question.user.login %></strong></td>
                <td>
                  <% if question.accepted_at? %>
                    Accepted at <%= question.accepted_at %>
                  <% elsif question.rejected_at? %>
                    Rejected at <%= question.rejected_at %>
                  <% else %>
                    <%= button_to "Accept", { :action => "accept", :id => question.id }, :method => :put, :class => "btn btn-primary" %><%= button_to "Reject", { :action => "reject", :id => question.id }, :method => :put, :class => "btn btn-primary" %>
                  <% end %>
                </td>
                <td><%= link_to "Show", question_path(question), :class=> 'btn' %></td>
              </tr>
            <% end %>
          </table>
        </div>
        <div class="display-overlay"></div>
        <div class="display-gradient"></div>
      </div>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="clearfix" id="container">
  <div id="wrapper">
    <div class="view-container">
      <div class="display">
        <div id="view-login" style="display: block;">
          <h2>Questionizer</h2>
          <%= render :partial => 'form' %>
          
        </div>
        <div class="display-overlay"></div>
        <div class="display-gradient"></div>
      </div>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="clearfix" id="container">
  <div id="wrapper">
    <div class="view-container">
      <div class="display">
        <div id="view-login" style="display: block;">
          <h2>Question</h2>
          <p>
            <b>Category</b><br>
            <%= @question.category %>
          </p>

          <p>
            <b>Sub category</b><br>
            <%= @question.sub_category %>
          </p>

          <p>
            <b>Nerd level</b><br>
            <%= @question.nerd_level %>
          </p>

          <p>
            <b>Text</b><br>
            <%= @question.text %>
          </p>

          <p>
            <b>A1</b><br>
            <%= @question.a1 %>
          </p>

          <p>
            <b>A2</b><br>
            <%= @question.a2 %>
          </p>

          <p>
            <b>A3</b><br>
            <%= @question.a3 %>
          </p>

          <p>
            <b>A4</b><br>
            <%= @question.a4 %>
          </p>

          <p>
            <b>Right answer</b><br>
            <%= @question.right_answer %>
          </p>

          <p>
            <b>Creator</b><br>
            <%= @question.creator %>
          </p>

          <p>
            <b>Creator twitter</b><br>
            <%= @question.creator_twitter %>
          </p>

          <p>
            <b>Creator github</b><br>
            <%= @question.creator_github %>
          </p>

          <p>
            <b>User</b><br>
            <%= @question.user_id %>
          </p>

          <div class="form-actions">
            <% if @question.accepted_at? %>
              Accepted at <%= @question.accepted_at %>
            <% elsif @question.rejected_at? %>
              Rejected at <%= @question.rejected_at %>
            <% else %>
              <%= button_to "Accept", { :action => "accept", :id => @question.id }, :method => :put, :class => "btn btn-primary" %><%= button_to "Reject", { :action => "reject", :id => @question.id }, :method => :put, :class => "btn btn-primary" %>
            <% end %>
            <%= link_to 'Back', questions_path, :class => 'btn'  %>
          </div>
          
        </div>
        <div class="display-overlay"></div>
        <div class="display-gradient"></div>
      </div>
    </div>
  </div>
</div>